In [5]:
import pandas as pd
print("Import Done")

Import Done

In [6]:
# Read the dataset
Investory = pd.read_csv(r"C:\Users\Abirami\OneDrive\Desktop\DE 6PM\Python\inventory_uncleaned_data.csv")
print("Read Done")

Read Done

In [7]:
# to read dataset
Investory = pd.read_csv("inventory_uncleaned_data.csv")
print("Read Done")

Read Done

In [9]:
# shape --> Dimensions of dataframe
Investory.shape

(50000, 10)

In [10]:
# To View data (Specific no of rows)
Investory.head()

,Product ID,Product Name,Category,Warehouse,Location,Quantity,Price,Supplier,Status,Last Restocked
0,1,widget b,TOYS,Warehouse 2,Aisle 4,two hundred,NaN,Supplier C,Out of Stock,05-03-2023
1,2,gadget x,ELECTRONICS,Warehouse 1,Aisle 4,two hundred,23.51,Supplier B,Out of Stock,20-12-2022
2,3,widget a,CLOTHING,Warehouse 3,Aisle 3,two hundred,29.83,Supplier B,In Stock,05-03-2023
3,4,gadget x,FURNITURE,Warehouse 3,Aisle 4,two hundred,NaN,Supplier A,Out of Stock,15-01-2023
4,5,gadget z,TOYS,Warehouse 3,Aisle 2,two hundred,26.03,Supplier A,Out of Stock,20-12-2022

In [11]:
# to find null counts
Investory.isnull().sum()

Product ID            0
Product Name          0
Category              0
Warehouse             0
Location              0
Quantity          16676
Price             25240
Supplier              0
Status                0
Last Restocked     9970
dtype: int64

In [12]:
# to replace null values
Investory.fillna({"Quantity":"0"},inplace = True)

,Product ID,Product Name,Category,Warehouse,Location,Quantity,Price,Supplier,Status,Last Restocked
0,1,widget b,TOYS,Warehouse 2,Aisle 4,two hundred,NaN,Supplier C,Out of Stock,05-03-2023
1,2,gadget x,ELECTRONICS,Warehouse 1,Aisle 4,two hundred,23.51,Supplier B,Out of Stock,20-12-2022
2,3,widget a,CLOTHING,Warehouse 3,Aisle 3,two hundred,29.83,Supplier B,In Stock,05-03-2023
3,4,gadget x,FURNITURE,Warehouse 3,Aisle 4,two hundred,NaN,Supplier A,Out of Stock,15-01-2023
4,5,gadget z,TOYS,Warehouse 3,Aisle 2,two hundred,26.03,Supplier A,Out of Stock,20-12-2022
...,...,...,...,...,...,...,...,...,...,...
49995,49996,gadget y,ELECTRONICS,Warehouse 2,Aisle 3,two hundred,NaN,Supplier C,Out of Stock,20-12-2022
49996,49997,gadget y,ELECTRONICS,Warehouse 3,Aisle 1,two hundred,NaN,Supplier C,In Stock,NaN
49997,49998,widget b,FURNITURE,Warehouse 2,Aisle 5,196,26.83,Supplier B,In Stock,NaN
49998,49999,gadget z,ELECTRONICS,Warehouse 1,Aisle 3,120,NaN,Supplier B,Low Stock,05-03-2023
49999,50000,gadget x,ELECTRONICS,Warehouse 3,Aisle 1,0,NaN,Supplier B,In Stock,20-12-2022

In [14]:
# to replace null values
Investory.fillna({"Price":"0"},inplace = True)
Investory.fillna({"Last Restocked":"0"},inplace = True)

,Product ID,Product Name,Category,Warehouse,Location,Quantity,Price,Supplier,Status,Last Restocked
0,1,widget b,TOYS,Warehouse 2,Aisle 4,two hundred,0,Supplier C,Out of Stock,05-03-2023
1,2,gadget x,ELECTRONICS,Warehouse 1,Aisle 4,two hundred,23.51,Supplier B,Out of Stock,20-12-2022
2,3,widget a,CLOTHING,Warehouse 3,Aisle 3,two hundred,29.83,Supplier B,In Stock,05-03-2023
3,4,gadget x,FURNITURE,Warehouse 3,Aisle 4,two hundred,0,Supplier A,Out of Stock,15-01-2023
4,5,gadget z,TOYS,Warehouse 3,Aisle 2,two hundred,26.03,Supplier A,Out of Stock,20-12-2022
...,...,...,...,...,...,...,...,...,...,...
49995,49996,gadget y,ELECTRONICS,Warehouse 2,Aisle 3,two hundred,0,Supplier C,Out of Stock,20-12-2022
49996,49997,gadget y,ELECTRONICS,Warehouse 3,Aisle 1,two hundred,0,Supplier C,In Stock,0
49997,49998,widget b,FURNITURE,Warehouse 2,Aisle 5,196,26.83,Supplier B,In Stock,0
49998,49999,gadget z,ELECTRONICS,Warehouse 1,Aisle 3,120,0,Supplier B,Low Stock,05-03-2023
49999,50000,gadget x,ELECTRONICS,Warehouse 3,Aisle 1,0,0,Supplier B,In Stock,20-12-2022

In [15]:
# to check null counts
Investory.isnull().sum()

Product ID        0
Product Name      0
Category          0
Warehouse         0
Location          0
Quantity          0
Price             0
Supplier          0
Status            0
Last Restocked    0
dtype: int64

In [17]:
# clean the column names
Investory.columns = (Investory.columns.str.strip().str.lower().str.replace(" ", "_"))

print("\nColumn names:")
print(Investory.columns)

Column names:
Index(['product_id', 'product_name', 'category', 'warehouse', 'location',
       'quantity', 'price', 'supplier', 'status', 'last_restocked'],
      dtype='str')

In [18]:
# Clean text columns
text_columns = [
    "product_name",
    "category",
    "warehouse",
    "location",
    "supplier",
    "status"
]

for column in text_columns:
    Investory[column] = Investory[column].astype("string").str.strip()

In [19]:
text_columns

['product_name', 'category', 'warehouse', 'location', 'supplier', 'status']

In [20]:
# Standardize text
Investory["product_name"] = Investory["product_name"].str.title()

Investory["category"] = Investory["category"].str.upper()

Investory["warehouse"] = Investory["warehouse"].str.title()

Investory["location"] = Investory["location"].str.title()

Investory["supplier"] = Investory["supplier"].str.title()

Investory["status"] = Investory["status"].str.title()

In [21]:
Investory

,product_id,product_name,category,warehouse,location,quantity,price,supplier,status,last_restocked
0,1,Widget B,TOYS,Warehouse 2,Aisle 4,two hundred,0,Supplier C,Out Of Stock,05-03-2023
1,2,Gadget X,ELECTRONICS,Warehouse 1,Aisle 4,two hundred,23.51,Supplier B,Out Of Stock,20-12-2022
2,3,Widget A,CLOTHING,Warehouse 3,Aisle 3,two hundred,29.83,Supplier B,In Stock,05-03-2023
3,4,Gadget X,FURNITURE,Warehouse 3,Aisle 4,two hundred,0,Supplier A,Out Of Stock,15-01-2023
4,5,Gadget Z,TOYS,Warehouse 3,Aisle 2,two hundred,26.03,Supplier A,Out Of Stock,20-12-2022
...,...,...,...,...,...,...,...,...,...,...
49995,49996,Gadget Y,ELECTRONICS,Warehouse 2,Aisle 3,two hundred,0,Supplier C,Out Of Stock,20-12-2022
49996,49997,Gadget Y,ELECTRONICS,Warehouse 3,Aisle 1,two hundred,0,Supplier C,In Stock,0
49997,49998,Widget B,FURNITURE,Warehouse 2,Aisle 5,196,26.83,Supplier B,In Stock,0
49998,49999,Gadget Z,ELECTRONICS,Warehouse 1,Aisle 3,120,0,Supplier B,Low Stock,05-03-2023
49999,50000,Gadget X,ELECTRONICS,Warehouse 3,Aisle 1,0,0,Supplier B,In Stock,20-12-2022

In [23]:
# Convert word "two hundred" to 200

Investory["quantity"] = Investory["quantity"].replace(
    {"two hundred": "200"}
)

In [25]:
# Convert quantity to numeric
Investory["quantity"] = pd.to_numeric(
    Investory["quantity"],
    errors="coerce"
)

In [26]:
# Fill missing quantity with median
Investory["quantity"] = Investory["quantity"].fillna(Investory["quantity"].median()
)

In [27]:
# Convert to datatype integer
Investory["quantity"] = Investory["quantity"].astype(int)

In [28]:
Investory

,product_id,product_name,category,warehouse,location,quantity,price,supplier,status,last_restocked
0,1,Widget B,TOYS,Warehouse 2,Aisle 4,200,0,Supplier C,Out Of Stock,05-03-2023
1,2,Gadget X,ELECTRONICS,Warehouse 1,Aisle 4,200,23.51,Supplier B,Out Of Stock,20-12-2022
2,3,Widget A,CLOTHING,Warehouse 3,Aisle 3,200,29.83,Supplier B,In Stock,05-03-2023
3,4,Gadget X,FURNITURE,Warehouse 3,Aisle 4,200,0,Supplier A,Out Of Stock,15-01-2023
4,5,Gadget Z,TOYS,Warehouse 3,Aisle 2,200,26.03,Supplier A,Out Of Stock,20-12-2022
...,...,...,...,...,...,...,...,...,...,...
49995,49996,Gadget Y,ELECTRONICS,Warehouse 2,Aisle 3,200,0,Supplier C,Out Of Stock,20-12-2022
49996,49997,Gadget Y,ELECTRONICS,Warehouse 3,Aisle 1,200,0,Supplier C,In Stock,0
49997,49998,Widget B,FURNITURE,Warehouse 2,Aisle 5,196,26.83,Supplier B,In Stock,0
49998,49999,Gadget Z,ELECTRONICS,Warehouse 1,Aisle 3,120,0,Supplier B,Low Stock,05-03-2023
49999,50000,Gadget X,ELECTRONICS,Warehouse 3,Aisle 1,0,0,Supplier B,In Stock,20-12-2022

In [29]:
Investory.describe()

         product_id      quantity
count  50000.000000  50000.000000
mean   25000.500000    125.210840
std    14433.901067     98.464493
min        1.000000      0.000000
25%    12500.750000      0.000000
50%    25000.500000    176.000000
75%    37500.250000    200.000000
max    50000.000000    300.000000

In [30]:
# Convert Last Restocked to date
Investory["last_restocked"] = pd.to_datetime(
    Investory["last_restocked"],
    format="%d-%m-%Y",
    errors="coerce"
)

In [31]:
Investory

,product_id,product_name,category,warehouse,location,quantity,price,supplier,status,last_restocked
0,1,Widget B,TOYS,Warehouse 2,Aisle 4,200,0,Supplier C,Out Of Stock,2023-03-05
1,2,Gadget X,ELECTRONICS,Warehouse 1,Aisle 4,200,23.51,Supplier B,Out Of Stock,2022-12-20
2,3,Widget A,CLOTHING,Warehouse 3,Aisle 3,200,29.83,Supplier B,In Stock,2023-03-05
3,4,Gadget X,FURNITURE,Warehouse 3,Aisle 4,200,0,Supplier A,Out Of Stock,2023-01-15
4,5,Gadget Z,TOYS,Warehouse 3,Aisle 2,200,26.03,Supplier A,Out Of Stock,2022-12-20
...,...,...,...,...,...,...,...,...,...,...
49995,49996,Gadget Y,ELECTRONICS,Warehouse 2,Aisle 3,200,0,Supplier C,Out Of Stock,2022-12-20
49996,49997,Gadget Y,ELECTRONICS,Warehouse 3,Aisle 1,200,0,Supplier C,In Stock,NaT
49997,49998,Widget B,FURNITURE,Warehouse 2,Aisle 5,196,26.83,Supplier B,In Stock,NaT
49998,49999,Gadget Z,ELECTRONICS,Warehouse 1,Aisle 3,120,0,Supplier B,Low Stock,2023-03-05
49999,50000,Gadget X,ELECTRONICS,Warehouse 3,Aisle 1,0,0,Supplier B,In Stock,2022-12-20

In [32]:
# Fill missing dates using the most common date
Investory["last_restocked"] = Investory["last_restocked"].fillna(
    Investory["last_restocked"].mode()[0]
)

In [33]:
Investory

,product_id,product_name,category,warehouse,location,quantity,price,supplier,status,last_restocked
0,1,Widget B,TOYS,Warehouse 2,Aisle 4,200,0,Supplier C,Out Of Stock,2023-03-05
1,2,Gadget X,ELECTRONICS,Warehouse 1,Aisle 4,200,23.51,Supplier B,Out Of Stock,2022-12-20
2,3,Widget A,CLOTHING,Warehouse 3,Aisle 3,200,29.83,Supplier B,In Stock,2023-03-05
3,4,Gadget X,FURNITURE,Warehouse 3,Aisle 4,200,0,Supplier A,Out Of Stock,2023-01-15
4,5,Gadget Z,TOYS,Warehouse 3,Aisle 2,200,26.03,Supplier A,Out Of Stock,2022-12-20
...,...,...,...,...,...,...,...,...,...,...
49995,49996,Gadget Y,ELECTRONICS,Warehouse 2,Aisle 3,200,0,Supplier C,Out Of Stock,2022-12-20
49996,49997,Gadget Y,ELECTRONICS,Warehouse 3,Aisle 1,200,0,Supplier C,In Stock,2023-04-25
49997,49998,Widget B,FURNITURE,Warehouse 2,Aisle 5,196,26.83,Supplier B,In Stock,2023-04-25
49998,49999,Gadget Z,ELECTRONICS,Warehouse 1,Aisle 3,120,0,Supplier B,Low Stock,2023-03-05
49999,50000,Gadget X,ELECTRONICS,Warehouse 3,Aisle 1,0,0,Supplier B,In Stock,2022-12-20

In [34]:
# Check final missing values
print("\nMissing values after cleaning:")
print(Investory.isnull().sum())

Missing values after cleaning:
product_id        0
product_name      0
category          0
warehouse         0
location          0
quantity          0
price             0
supplier          0
status            0
last_restocked    0
dtype: int64

In [35]:
# Check data types
print("\nFinal data types:")
print(Investory.dtypes)

Final data types:
product_id                 int64
product_name              string
category                  string
warehouse                 string
location                  string
quantity                   int64
price                     object
supplier                  string
status                    string
last_restocked    datetime64[us]
dtype: object

In [36]:
 # Check cleaned data
print("\nCleaned dataset:")
print(Investory.head())

print("\nDataset shape:")
print(Investory.shape)

Cleaned dataset:
   product_id product_name     category    warehouse location  quantity  \
0           1     Widget B         TOYS  Warehouse 2  Aisle 4       200
1           2     Gadget X  ELECTRONICS  Warehouse 1  Aisle 4       200
2           3     Widget A     CLOTHING  Warehouse 3  Aisle 3       200
3           4     Gadget X    FURNITURE  Warehouse 3  Aisle 4       200
4           5     Gadget Z         TOYS  Warehouse 3  Aisle 2       200

   price    supplier        status last_restocked
0      0  Supplier C  Out Of Stock     2023-03-05
1  23.51  Supplier B  Out Of Stock     2022-12-20
2  29.83  Supplier B      In Stock     2023-03-05
3      0  Supplier A  Out Of Stock     2023-01-15
4  26.03  Supplier A  Out Of Stock     2022-12-20

Dataset shape:
(50000, 10)

In [37]:
# Save cleaned dataset
Investory.to_csv("inventory_cleaned_data.csv",index=False)

print("\nCleaned file saved successfully!")

Cleaned file saved successfully!